#!/usr/bin/env bash

(
  cd /opt/app/S2OPC/build/bin
  export TEST_SERVER_XML_CONFIG=./S2OPC_Server_Demo_Config.xml
  export TEST_SERVER_XML_ADDRESS_SPACE=./S2OPC_Demo_NodeSet.xml
  export TEST_USERS_XML_CONFIG=./S2OPC_Users_Demo_Config.xml
  ./toolkit_demo_server 
)

exit 0
